version: "3.2"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.2
    tty: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: always
    hostname: app
    working_dir: /var/www/html
    expose:
      - 9000
      - 9001
    volumes:
      - ./:/var/www/html:cached
      - ./:/var/run/php-fpm/
      - ./docker/nginx/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - database
  nginx:
    image: nginx:1.19.0
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    tty: true
    expose:
      - "80"
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/logs:/var/log/nginx/
    depends_on:
      - app

  # The Database
  database:
    image: postgres:15
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: always
    platform: linux/x86_64
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - ${DOCKER_DATABASE_PORT}:5432
  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    expose:
      - "6379"
    ports:
      - ${DOCKER_REDIS_PORT}:6379
